using System;
using System.Collections.Generic;
using System.Text;

namespace AutoRest.Ansible.Model
{
    /// <summary>
    /// MapAnsible contains all necessary information to generate ansible modules.
    /// Information comes from 2 sources:
    ///  - REST API Specification
    ///  - Applied external tweaks
    ///  This class is designed to be easily serialised to JSON file.
    ///  Tweaks can be then applied to that JSON file and it can be easily merged with next version of autogenerated MapAnsible
    /// </summary>

    public class ModuleOption
    {
        public ModuleOption(string name, string type, string required, string variableValue)
        {
            Name = name; NameAlt = name; Type = type; Required = required; VariableValue = variableValue;
            RequiredCount = 0;
            SubOptions = null;
            IsList = false;
            Disposition = "default";
            DefaultValueSample = "\"{{ " + NameAlt + " }}\"";
            DefaultValueTest = "";
        }

        public string Name { get; set; }
        public string NameAlt { get; set; }

        // For first level options:
        //  "default" - module variable will be created
        //  "dictionary" - option is hidden (doesn't appear on list of parameters) and is used to store flattened level values
        //  [dictionary name] - option is flattened from second level and should be stored in [dictionary name]
        public string Disposition { get; set; }
        public string Type { get; set; }
        public bool IsList { get; set; }
        public string Required { get; set; }
        public string VariableValue { get; set; }
        public string Documentation { get; set; }
        public string DefaultValueSample { get; set; }
        public string DefaultValueTest { get; set; }
        public ModuleOption[] SubOptions { get; set; }
        public int RequiredCount { get; set; }
    }

    public class ModuleMethod
    {
        public string Name { get; set; }

        public string[] Options { get; set; }
        public string[] RequiredOptions { get; set; }
    }

    public class MapAnsibleModule
    {
        public string ModuleName { get; set; }
        public string ModuleNameAlt { get; set; }
        public ModuleOption[] Options { get; set; }
        public ModuleMethod[] Methods { get; set; }

        public string TestPrerequisitesModule { get; set; }
        public string AssertStateVariable { get; set; }
        public string AssertStateExpectedValue { get; set; }
        public string ModuleOperationNameUpper { get; set; }
        public string ModuleOperationName { get; set; }
        public string ObjectName { get; set; }
    }

    public class MapAnsible
    {
        public MapAnsibleModule[] Modules { get; set; }

        public string Namespace { get; set; }
        public string NamespaceUpper { get; set; }
        public string Name { get; set; }
        public string[] Operations { get; set; }
    }
}
