- azure_rm_guestconfigurationassignment:
- azure_rm_guestconfigurationassignment.guest_configuration_assignment_name:
- azure_rm_guestconfigurationassignment.parameters:
- azure_rm_guestconfigurationassignment.parameters.properties:
- azure_rm_guestconfigurationassignment.parameters.properties.guest_configuration:
- azure_rm_guestconfigurationassignment.parameters.properties.guest_configuration.kind:
- azure_rm_guestconfigurationassignment.parameters.properties.guest_configuration.name:
- azure_rm_guestconfigurationassignment.parameters.properties.guest_configuration.version:
- azure_rm_guestconfigurationassignment.parameters.properties.guest_configuration.configuration_parameter:
- azure_rm_guestconfigurationassignment.parameters.properties.guest_configuration.configuration_setting:
- azure_rm_guestconfigurationassignment.parameters.properties.guest_configuration.configuration_setting.allow_module_overwrite:
- azure_rm_guestconfigurationassignment.parameters.properties.context:
- azure_rm_guestconfigurationassignment.resource_group_name:
- azure_rm_guestconfigurationassignment.vm_name:
- azure_rm_guestconfigurationassignment.response.id:
- azure_rm_guestconfigurationassignment.response.name:
- azure_rm_guestconfigurationassignment.response.location:
- azure_rm_guestconfigurationassignment.response.type:
- azure_rm_guestconfigurationassignment.response.properties:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.kind:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.name:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.version:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.content_uri:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.content_hash:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_parameter:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_parameter.name:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_parameter.value:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_setting:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_setting.configuration_mode:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_setting.allow_module_overwrite:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_setting.action_after_reboot:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_setting.refresh_frequency_mins:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_setting.reboot_if_needed:
- azure_rm_guestconfigurationassignment.response.properties.guest_configuration.configuration_setting.configuration_mode_frequency_mins:
- azure_rm_guestconfigurationassignment.response.properties.compliance_status:
- azure_rm_guestconfigurationassignment.response.properties.last_compliance_status_checked:
- azure_rm_guestconfigurationassignment.response.properties.latest_report_id:
- azure_rm_guestconfigurationassignment.response.properties.context:
- azure_rm_guestconfigurationassignment.response.properties.assignment_hash:
- azure_rm_guestconfigurationassignment.response.properties.provisioning_state:
- azure_rm_guestconfigurationassignment_facts:
- azure_rm_guestconfigurationassignment_facts.resource_group_name:
- azure_rm_guestconfigurationassignment_facts.guest_configuration_assignment_name:
- azure_rm_guestconfigurationassignment_facts.vm_name:
- azure_rm_guestconfigurationassignment_facts.response.id:
- azure_rm_guestconfigurationassignment_facts.response.name:
- azure_rm_guestconfigurationassignment_facts.response.location:
- azure_rm_guestconfigurationassignment_facts.response.type:
- azure_rm_guestconfigurationassignment_facts.response.properties:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.kind:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.name:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.version:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.content_uri:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.content_hash:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_parameter:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_parameter.name:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_parameter.value:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_setting:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_setting.configuration_mode:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_setting.allow_module_overwrite:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_setting.action_after_reboot:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_setting.refresh_frequency_mins:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_setting.reboot_if_needed:
- azure_rm_guestconfigurationassignment_facts.response.properties.guest_configuration.configuration_setting.configuration_mode_frequency_mins:
- azure_rm_guestconfigurationassignment_facts.response.properties.compliance_status:
- azure_rm_guestconfigurationassignment_facts.response.properties.last_compliance_status_checked:
- azure_rm_guestconfigurationassignment_facts.response.properties.latest_report_id:
- azure_rm_guestconfigurationassignment_facts.response.properties.context:
- azure_rm_guestconfigurationassignment_facts.response.properties.assignment_hash:
- azure_rm_guestconfigurationassignment_facts.response.properties.provisioning_state:
- azure_rm_guestconfigurationassignmentreport_facts:
- azure_rm_guestconfigurationassignmentreport_facts.resource_group_name:
- azure_rm_guestconfigurationassignmentreport_facts.guest_configuration_assignment_name:
- azure_rm_guestconfigurationassignmentreport_facts.report_id:
- azure_rm_guestconfigurationassignmentreport_facts.vm_name:
- azure_rm_guestconfigurationassignmentreport_facts.response.id:
- azure_rm_guestconfigurationassignmentreport_facts.response.name:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.compliance_status:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.report_id:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.assignment:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.assignment.name:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.assignment.configuration:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.assignment.configuration.name:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.vm:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.vm.id:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.vm.uuid:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.compliance_status:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.start_time:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.end_time:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.job_id:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.operation_type:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.resources:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.resources.compliance_status:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.resources.reasons:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.resources.reasons.phrase:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.resources.reasons.code:
- azure_rm_guestconfigurationassignmentreport_facts.response.properties.details.resources.properties:
- azure_rm_guestconfigurationsoftware_facts:
- azure_rm_guestconfigurationsoftware_facts.resource_group_name:
- azure_rm_guestconfigurationsoftware_facts.vm_name:
- azure_rm_guestconfigurationsoftware_facts.software_id:
