sudo: required

services:
  - docker

script:
  - cd dockerfile-inc && docker build --tag dockiot/autorest-ansible-inc .
  - git clone https://github.com/zikalino/ansible-hatchery.git
  - mkdir tmp
  - echo $TRAVIS_BUILD_DIR
  - docker run --name autorest-ansible -v $TRAVIS_BUILD_DIR/ansible-hatchery:/ansible-hatchery -v $TRAVIS_BUILD_DIR/tmp:/ansible-hatchery-tmp dockiot/autorest-ansible-inc all


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push dockiot/autorest-ansible-inc;
    fi

