sudo: required

services:
  - docker

script:
  - cd dockerfile-inc && docker build --tag dockiot/autorest-ansible-inc .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push dockiot/autorest-ansible-inc;
    fi

