sudo: required

services:
  - docker

script:
  - cd dockerfile && docker build --tag dockiot/autorest-ansible .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push dockiot/autorest-ansible;
    fi
